base_images:
  base:
    name: "4.8"
    namespace: ocp
    tag: base
binary_build_commands: make managers clusterctl
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.16
images:
- dockerfile_path: Dockerfile
  from: base
  to: cluster-api
promotion:
  namespace: hypershift
  registry_override: quay.io/openshift
  tag: hypershift
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
  unit:
    requests:
      cpu: 100m
      memory: 400Mi
tag_specification:
  name: hypershift
  namespace: ocp
zz_generated_metadata:
  branch: openshift-hypershift
  org: openshift
  repo: cluster-api
